# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ul2zjhpKll27HGQtN5MkBwG2eexC__gY
"""

# The skeleton codes for the ELEC378 Final Project to load the dataset and help you get started
# Author: Rocky Ren, Harvey Chen, Matthew Karazincir
# Modified: Added CNN model trained from scratch

import os
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

from google.colab import drive
drive.mount('/content/drive')

# Modify these paths to match your dataset.
project_base_path = '/content/drive/My Drive/ELEC 378 Final Project - MKTA Intelligence/'
TRAIN_IMG_DIR = os.path.join(project_base_path, 'train_images')
TEST_IMG_DIR  = os.path.join(project_base_path, 'test_images')
CSV_PATH      = os.path.join(project_base_path, 'train.csv')

RANDOM_STATE = 42  # This is for the reproducibility of the train test split.
IMG_SIZE     = 64  # Input image size (64x64 is a good balance of speed vs accuracy)
BATCH_SIZE   = 32
NUM_CLASSES  = 100

# Sanity check
print(f"Contents of train_images: {os.listdir(TRAIN_IMG_DIR)[:5]}")
print(f"GPU available: {tf.config.list_physical_devices('GPU')}")

# Loads the metadata from the csv file
def load_metadata():
    df = pd.read_csv(CSV_PATH)
    df["file_name"] = df["file_name"].apply(lambda x: os.path.basename(x))
    print(f"Loaded {len(df)} entries, {df['TARGET'].nunique()} classes")
    return df

# Loads the images
def load_image(filename, size):
    path = filename
    img = Image.open(path).convert("RGB").resize((size, size))
    return np.array(img)

# Build a tf.data pipeline for efficient loading and augmentation
def build_dataset(filepaths, labels, training=False):
    ds = tf.data.Dataset.from_tensor_slices((filepaths, labels))

    def parse(path, label):
        img = tf.io.read_file(path)
        img = tf.image.decode_jpeg(img, channels=3)
        img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])
        img = tf.cast(img, tf.float32) / 255.0  # normalize to [0, 1]
        return img, label

    def augment(img, label):
        img = tf.image.random_flip_left_right(img)
        img = tf.image.random_brightness(img, max_delta=0.2)
        img = tf.image.random_contrast(img, lower=0.8, upper=1.2)
        img = tf.image.random_saturation(img, lower=0.8, upper=1.2)
        # Random crop for slight zoom effect
        img = tf.image.resize_with_crop_or_pad(img, IMG_SIZE + 8, IMG_SIZE + 8)
        img = tf.image.random_crop(img, size=[IMG_SIZE, IMG_SIZE, 3])
        return img, label

    ds = ds.map(parse, num_parallel_calls=tf.data.AUTOTUNE)
    if training:
        ds = ds.map(augment, num_parallel_calls=tf.data.AUTOTUNE)
        ds = ds.shuffle(buffer_size=2000, seed=RANDOM_STATE)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

# Build a CNN from scratch — no pretrained weights
def build_cnn(num_classes):
    """
    A moderately deep CNN trained entirely from scratch.
    Architecture: repeated Conv -> BN -> ReLU -> MaxPool blocks,
    followed by a fully connected head with dropout.
    """
    model = keras.Sequential([
        keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3)),

        # Block 1
        layers.Conv2D(32, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.Conv2D(32, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        # Block 2
        layers.Conv2D(64, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.Conv2D(64, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        # Block 3
        layers.Conv2D(128, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.Conv2D(128, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        # Block 4
        layers.Conv2D(256, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.Conv2D(256, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        # Classifier head
        layers.GlobalAveragePooling2D(),
        layers.Dense(512, activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation='softmax'),
    ])
    return model

def makeSubmission(ids, predictions, file="submission_cnn.csv"):
    submission = np.column_stack((ids, predictions))
    submission = np.vstack((['ID', 'TARGET'], submission))
    np.savetxt(file, submission, delimiter=',', fmt='%s')
    print(f"Submission saved to {file}")

def plot_history(history):
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'],     label='Train')
    plt.plot(history.history['val_accuracy'], label='Val')
    plt.xlabel('Epoch'); plt.ylabel('Accuracy')
    plt.title('Accuracy'); plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'],     label='Train')
    plt.plot(history.history['val_loss'], label='Val')
    plt.xlabel('Epoch'); plt.ylabel('Loss')
    plt.title('Loss'); plt.legend()

    plt.tight_layout()
    plt.savefig("cnn_training_history.png", dpi=150)
    plt.show()
    print("Saved cnn_training_history.png")

def main():
    print("Loading the ELEC378 Final Project Dataset")

    df = load_metadata()
    print("Loading csv done")

    # Encode string labels to integers
    classes      = sorted(df["TARGET"].unique())
    class_to_idx = {c: i for i, c in enumerate(classes)}
    idx_to_class = {i: c for c, i in class_to_idx.items()}
    df["label"]  = df["TARGET"].map(class_to_idx)

    X_train_files, X_val_files, y_train, y_val = train_test_split(
        df["file_name"].values,
        df["label"].values,
        test_size    = 0.2,
        stratify     = df["label"].values,
        random_state = RANDOM_STATE,
    )
    print(f"Train: {len(X_train_files)}, Validation: {len(X_val_files)}")

    # Build full file paths
    train_paths = [os.path.join(TRAIN_IMG_DIR, f) for f in X_train_files]
    val_paths   = [os.path.join(TRAIN_IMG_DIR, f) for f in X_val_files]

    # Build tf.data datasets
    train_ds = build_dataset(train_paths, y_train, training=True)
    val_ds   = build_dataset(val_paths,   y_val,   training=False)

    # Build and compile model
    model = build_cnn(NUM_CLASSES)
    model.compile(
        optimizer = keras.optimizers.Adam(learning_rate=1e-3),
        loss      = 'sparse_categorical_crossentropy',
        metrics   = ['accuracy']
    )
    model.summary()

    callbacks = [
        EarlyStopping(monitor='val_accuracy', patience=5,
                      restore_best_weights=True, verbose=1),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                          patience=3, min_lr=1e-6, verbose=1),
        ModelCheckpoint('best_cnn_model.keras', monitor='val_accuracy',
                        save_best_only=True, verbose=1),
    ]

    print("\nTraining CNN from scratch …")
    history = model.fit(
        train_ds,
        validation_data = val_ds,
        epochs          = 30,
        callbacks       = callbacks,
    )

    print(f"\nBest val accuracy: {max(history.history['val_accuracy']):.4f}")
    plot_history(history)

    # Generate test predictions
    print("\nGenerating test predictions …")
    testFiles = [f"test_{j:06d}.jpg" for j in range(1, 1001)]
    testIds   = [f"test_{j:06d}"     for j in range(1, 1001)]
    test_paths = [os.path.join(TEST_IMG_DIR, f) for f in testFiles]

    test_ds = tf.data.Dataset.from_tensor_slices(test_paths)
    test_ds = test_ds.map(
        lambda p: tf.cast(
            tf.image.resize(
                tf.image.decode_jpeg(tf.io.read_file(p), channels=3),
                [IMG_SIZE, IMG_SIZE]
            ), tf.float32) / 255.0,
        num_parallel_calls=tf.data.AUTOTUNE
    ).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

    preds_probs  = model.predict(test_ds, verbose=1)
    preds_idx    = np.argmax(preds_probs, axis=1)
    preds_labels = [idx_to_class[i] for i in preds_idx]

    makeSubmission(testIds, preds_labels)
    print("\nDone!")

main()