# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AuJLGTs2fcum3tV26f4i2yCNSNiCIOAg
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

project_base_path = '/content/drive/My Drive/ELEC 378 Final Project - MKTA Intelligence/'

# Corrected paths: Remove the duplication of folder names in the os.path.join calls
TRAIN_IMG_DIR     = os.path.join(project_base_path, 'train_images')
TEST_IMG_DIR      = os.path.join(project_base_path, 'test_images')
CSV_PATH          = os.path.join(project_base_path, 'train.csv')

# Sanity check
print(f"Contents of train_images: {os.listdir(TRAIN_IMG_DIR)[:10]}")
print(f"Contents of test_images:  {os.listdir(TEST_IMG_DIR)[:10]}")

from google.colab import drive
drive.mount('/content/drive')

#Image Helpers

def load_metadata():
    df = pd.read_csv(CSV_PATH)
    # If filenames look like 'train_images/train_008045.jpg', strip the folder
    df["file_name"] = df["file_name"].apply(lambda x: os.path.basename(x))
    print(f"Loaded {len(df)} entries, {df['TARGET'].nunique()} classes")
    return df

def load_image(path, size=64):
    return np.array(Image.open(path).convert("RGB").resize((size, size)))

def imgToFeatureMatrix(imgPath, imgFiles, labelList, count=0, step=0):
    """Flatten pixel data into a 2-D feature matrix.
    Identical interface to the version in skeleton.py so the two scripts
    are directly comparable.
    """
    n = len(imgFiles)
    if count == 0:
        count = n
    if step == 0:
        step = max(1, n // count)

    features, labels = [], []
    for i in range(0, n, step):
        if len(features) >= count:
            break
        path = os.path.join(imgPath, imgFiles[i])
        img  = load_image(path, size=64)
        features.append(img.flatten() / 255.0)
        labels.append(labelList[i])

    return np.array(labels), np.array(features)

def train_random_forest(X_train, X_val, y_train, y_val, le,
                        n_estimators=200, max_depth=None,
                        min_samples_leaf=2, max_features="sqrt"):
    y_train_enc = le.transform(np.ravel(y_train))
    y_val_enc   = le.transform(np.ravel(y_val))

    print(f"Training Random Forest  |  trees={n_estimators}, "
          f"max_depth={max_depth}, min_samples_leaf={min_samples_leaf}, "
          f"max_features={max_features}")

    rf = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        n_jobs=-1,
        random_state=RANDOM_STATE,
        class_weight="balanced",
    )
    rf.fit(X_train, y_train_enc)

    val_preds = rf.predict(X_val)
    val_acc   = accuracy_score(y_val_enc, val_preds)
    print(f"Validation accuracy: {val_acc:.4f}\n")
    print(classification_report(y_val_enc, val_preds, zero_division=0))

    return rf, le

#Feature Important plot

def plot_feature_importance(rf, top_n=30, img_size=224):
    """Plot the top-N most important pixels (useful for the report)."""
    importances = rf.feature_importances_        # shape: (224*224*3,)
    top_idx     = np.argsort(importances)[::-1][:top_n]

    plt.figure(figsize=(12, 4))
    plt.bar(range(top_n), importances[top_idx])
    plt.xlabel("Pixel index (ranked)")
    plt.ylabel("Importance")
    plt.title(f"Top {top_n} pixel importances – Random Forest")
    plt.tight_layout()
    plt.savefig("rf_feature_importance.png", dpi=150)
    plt.show()
    print("Saved rf_feature_importance.png")

def makeSubmission(ids, predictions, file="submission_rf.csv"):
    submission = np.column_stack((ids, predictions))
    submission = np.vstack((['ID', 'TARGET'], submission))
    np.savetxt(file, submission, delimiter=',', fmt='%s')
    print(f"Submission saved to {file}")

def main():
    print("=" * 60)
    print("ELEC378 Final Project – Random Forest Classifier")
    print("=" * 60)

    df = load_metadata()

    X_train_files, X_val_files, y_train, y_val = train_test_split(
        df["file_name"].values,
        df["TARGET"].values,
        test_size    = 0.2,
        stratify     = df["TARGET"].values,
        random_state = RANDOM_STATE,
    )
    print(f"Train: {len(X_train_files)}  |  Val: {len(X_val_files)}")

#Build Test Files
testFiles = [f"test_{j:06d}.jpg" for j in range(1, 1001)]
testIds   = [f"test_{j:06d}"     for j in range(1, 1001)]

# Increase `count` when you're ready for a full run (or remove it entirely).
print("\nExtracting training features …")
trainLabels, trainMatrix = imgToFeatureMatrix(TRAIN_IMG_DIR, X_train_files, y_train, count=500)

print("Extracting validation features …")
    valLabels, valMatrix = imgToFeatureMatrix(
        TRAIN_IMG_DIR, X_val_files, y_val, count=300)

print("Extracting test features …")
    _, testMatrix = imgToFeatureMatrix(
        TEST_IMG_DIR, testFiles, ["placeholder"] * len(testFiles), count=0)

#Train

rf, le = train_random_forest(
        trainMatrix, valMatrix,
        trainLabels, valLabels,
        n_estimators    = 200,
        max_depth       = None,
        min_samples_leaf= 2,
        max_features    = "sqrt",
    )

RANDOM_STATE = 42

def main():
    print("=" * 60)
    print("ELEC378 Final Project – Random Forest Classifier")
    print("=" * 60)

    df = load_metadata()

    X_train_files, X_val_files, y_train, y_val = train_test_split(
        df["file_name"].values,
        df["TARGET"].values,
        test_size=0.2,
        stratify=df["TARGET"].values,
        random_state=RANDOM_STATE,
    )
    print(f"Train: {len(X_train_files)}  |  Val: {len(X_val_files)}")

    # Fit LabelEncoder on ALL classes before subsampling
    le = LabelEncoder()
    le.fit(df["TARGET"].values)

    # Build Test Files
    testFiles = [f"test_{j:06d}.jpg" for j in range(1, 1001)]
    testIds   = [f"test_{j:06d}"     for j in range(1, 1001)]

    print("\nExtracting training features …")
    trainLabels, trainMatrix = imgToFeatureMatrix(TRAIN_IMG_DIR, X_train_files, y_train, count=0)

    print("Extracting validation features …")
    valLabels, valMatrix = imgToFeatureMatrix(TRAIN_IMG_DIR, X_val_files, y_val, count=0)

    print("Extracting test features …")
    _, testMatrix = imgToFeatureMatrix(TEST_IMG_DIR, testFiles, ["placeholder"] * len(testFiles), count=0)

    # Train
    rf, le = train_random_forest(
        trainMatrix, valMatrix,
        trainLabels, valLabels,
        le,
        n_estimators=200,
        max_depth=None,
        min_samples_leaf=2,
        max_features="sqrt",
    )

    # submit
    test_preds_enc = rf.predict(testMatrix)
    test_preds = le.inverse_transform(test_preds_enc)
    makeSubmission(testIds, test_preds)

main()